Algoritmo "Adição"

// Descrição   : Adição de dois números
// Autor(a)    : Giovana
// Data atual  : 13/08/2020
Var
   // Seção de Declarações
   num1, num2: inteiro
   soma: inteiro

Inicio
   // Seção de Comandos
   Escreval ("Informe o primeiro número: ")
   Leia (num1)

   Escreval ("Informe o segundo número: ")
   Leia (num2)

   Escreval ("A soma é: ",num1,"+",num2)

   soma<- num1+num2
   Escreval ("E o resultado é: ",soma)

Fimalgoritmo