Algoritmo "AntecessorSucessor"

// Descrição   : Informar antecessor e sucessor de um número
// Autor(a)    : Giovana
// Data atual  : 13/08/2020
Var
// Seção de Declarações
Numero: inteiro
Antecessor: inteiro
Sucessor: inteiro

Inicio
// Seção de Comandos
Escreval ("Informe um número: ")
Leia (numero)
Escreval ()
Antecessor<- numero-1
Escreval ("O antecessor deste número: ",antecessor)

Sucessor<- numero+1
Escreval ("O sucessor deste número: ",sucessor)

Fimalgoritmo