Algoritmo "Temperatura"

// Descrição   : Conversão de Celsius para Fahrenheit
// Autor(a)    : Giovana
// Data atual  : 13/08/2020
Var
   // Seção de Declarações
   temperatura_f, temperatura_c: real

Inicio
   // Seção de Comandos
   Escreva ("Informe a temperatura do ambiente em °C (graus celsius): ")
   Leia (temperatura_c)
   Escreval ()
   temperatura_f<- (9*temperatura_c+160)/5
   Escreva ("Essa temperatura em °F (fahrenheit) é:",temperatura_f)
   Escreval ()
Fimalgoritmo