Algoritmo "ÁreaTriângulo"

// Descrição   : Calcular área do triângulo
// Autor(a)    : Giovana
// Data atual  : 13/08/2020
Var
   // Seção de Declarações
   area: real
   base: real
   altura: real

Inicio
   // Seção de Comandos
   Escreval ("Informe o total da base do triângulo: ")
   Leia (base)

   Escreval ("Informe a altura do triângulo: ")
   Leia (altura)

   area<- (base*altura)/2
   Escreval ("A área total do triângulo é: ",area)

Fimalgoritmo