Algoritmo "Área"

// Descrição   : Calcular a área
// Autor(a)    : Giovana
// Data atual  : 13/08/2020
Var
   // Seção de Declarações
   area: real
   constante_pi: real
   raio: real

Inicio
   // Seção de Comandos
   Escreva ("Informe o valor do raio: ")
   Leia (raio)

   constante_pi<- 3,14159
   area<- constante_pi*raio ²
   Escreval ("O total da área da circunferência é: ",area)

Fimalgoritmo